### ISSUE TITLE
Cmake list

### ISSUE THREAD

**Issue by MyVanitar** [ValentiWorkLearning/GradWork#28]
Hi,

The Cmake list of `.c` files has been changed by the new updates of the LVGL. I appreciate if you update it

**Comment by ValentiWorkLearning** [comment]
@MyVanitar hello. I've updated them to be up-to-date with the LVGL version.

**Comment by ValentiWorkLearning** [comment]
@MyVanitar Just use $ find . -name "*.c" > allcfiles.txt for generate list of c-files for CMakeLists of lvlgl. and then copy-paste the result to your CMakeLists where you have to specify the library sources list
